export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const ADD_ITEM_TO_CART = "ADD_TO_CART";
export const REMOVE_ITEM_FROM_CART =" REMOVE_ITEM_FROM_CART";
export const CLEAR_ITEM_FROM_CART = "CLEAR_ITEM_FROM_CART";
export const CLEAR_ALL_ITEMS_FROM_CART = "CLEAR_ALL_ITEMS_FROM_CART";
export const GET_USER_CART_ITEMS = "GET_USER_CART_ITEMS";
export const CART_BUTTON = "CART_BUTTON";

